# Generated by Django 2.2.5 on 2019-10-23 09:07

from django.db import migrations, models
import django.db.models.deletion
from log.migrate_data import populate


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'log types',
                'db_table': 'LogType',
            },
        ),
        migrations.AddField(
            model_name='log',
            name='log_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='log.LogType'),
            preserve_default=False,
        ),

        migrations.RunPython(populate, reverse_code=migrations.RunPython.noop)
    ]
