# Generated by Django 2.2.5 on 2019-10-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_remove_person_friendly'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
