# Generated by Django 2.2.5 on 2019-10-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_auto_20191001_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='height',
            field=models.DecimalField(decimal_places=2, default=1.65, max_digits=10),
        ),
    ]
